config/routes.rb
GroupsyDaisy::Application.routes.draw do
  
  root to: "trips#index"
  
  devise_for :users
  
  get "static/index"

  match 'orders/:id/new' => 'orders#new', :as => :new_order
  match 'trips/public/:id' => 'trips#public_show', as: :public_trip #use public_trip_url(trip_id)
  match 'trips/email_publicize_new/:id' => 'trips#email_publicize_new', as: :email_publicize #email_publicize_path(trip_id)
  match 'trips/email_publicize_create/:id' => 'trips#email_publicize_create', as: :email_publicize_create
  match 'trips/email_participants_new/:id' => 'trips#email_participants_new', as: :email_participants
  match 'trips/email_participants_create/:id' => 'trips#email_participants_create', as: :email_participants_create
  put 'line_items' => 'line_items#update', as: :update_line_items
  put 'orders' => 'orders#update_multiple', as: :update_orders
  
  resources :orders

  resources :line_items

  resources :items

  resources :trips

  resources :groups

  resources :destination_specific_activities

  resources :activities

  resources :destinations

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :group
  belongs_to :destination_specific_activity
  belongs_to :leader, class_name: 'User', foreign_key: :leader
  has_many :orders, dependent: :destroy
  has_many :contacts, dependent: :destroy
  attr_accessible :date, :leader, :group, :destination_specific_activity, :payment_instructions
  validates :date, :leader, :group_id, :destination_specific_activity_id, presence: true
  validate :date_cannot_be_in_past
  
  def date_cannot_be_in_past
    if self.date < Date.today
      errors.add(:date, "cannot be in the past")
    end
  end
  
  def to_s
    self.destination_specific_activity.activity.to_s.capitalize + ' with ' + self.group.to_s + ' on ' + self.date.to_s
  end
  
  def total_amount_due
    sum = 0
    self.orders.each {|order| sum += order.total_amount_due}
    sum
  end
  
  def item_count(item)
    sum = 0
    self.orders.each {|order| sum += order.item_count(item)}
    sum
  end
  
  def user_registered?(user)
    result = Order.where("user_id = :user_id and trip_id = :trip_id", {user_id: user.id, trip_id: self.id})
    if result.empty?
      return false
    else
      return true
    end
  end
  
  def is_leader?(user)
    self.leader.id == user.id
  end
  
  def activity
    self.destination_specific_activity.activity.name
  end
  
  def destination
    self.destination_specific_activity.destination
  end
  
  def publicize_text
    text = "On #{self.date} #{self.group} is planning a trip to go #{self.activity} at #{self.destination}."
    text += " #{self.leader} will be leading the trip. "
    #text += "Get details and sign up online at #{Rails.application.routes.url_helpers.public_trip_url(self.id, host: 'groupsydaisy.com')}."
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  # GET /trips
  # GET /trips.json
  skip_before_filter :authenticate_user!, :only => [:public_show]
  load_and_authorize_resource except: :public_show #cancancan
  skip_authorization_check :only => [:public_show]
  def index
    @trips = Trip.where "date >= ?", Date.current

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trips }
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])
    @order = Order.find_by_trip_id_and_user_id(@trip.id, current_user.id)
    respond_to do |format|
      format.html #{render layout: 'trip'}# show.html.erb
      format.json { render json: @trip }
    end
  end
  
  def public_show
    @trip = Trip.find(params[:id])
    if current_user
      @order = Order.find_by_user_id_and_trip_id(current_user.id, @trip.id)
    end
    respond_to do |format|
      format.html #{render layout: 'trip'}# show.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/new
  # GET /trips/new.json
  def new
    @trip = Trip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/1/edit
  def edit
    @trip = Trip.find(params[:id])
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(params[:trip])

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render json: @trip, status: :created, location: @trip }
      else
        format.html { render action: "new" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.json
  def update
    @trip = Trip.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end
  
  def email_publicize_new
    @trip = Trip.find(params[:id])
  end
  
  def email_participants_new
    @trip = Trip.find(params[:id])
  end
  
  def email_participants_create
    @trip = Trip.find(params[:id])
    @addresses = @trip.orders.map{|order| order.user.email}
    UserMailer.send_email_participants(@trip, @addresses, params[:subject], params[:message])
    redirect_to trip_url(@trip)
  end
  def email_publicize_create
    @trip = Trip.find(params[:id])
    @addresses = params[:addresses].split(",").map(&:strip)
    @addresses.each{|address| Contact.create( {email: address, trip_id: @trip.id})}
    UserMailer.send_publicize_trip(@addresses, @trip, params[:message])
    redirect_to trip_url(@trip)
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :group %><br />
    <%= f.text_field :group %>
  </div>
  <div class="field">
    <%= f.label :destination_specific_activity %><br />
    <%= f.text_field :destination_specific_activity %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :leader %><br />
    <%= f.number_field :leader %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/_leader.html.erb
<h2>Trip Information for Leader</h2>
<%= form_tag '/orders', method: :put %>
<p>
	<table>
		<tr>
			<th>
				Name
			</th>
			<% @trip.destination_specific_activity.items.each do |item| %>
				<th>
					<%= item.name.capitalize.pluralize %>
				</th>
				
			<% end %>	
				<th>
					Amount due
				</th>
				<th>
					Paid?
				</th>
		</tr>		
				<%= hidden_field_tag :trip_id, @trip.id %>
				<% @trip.orders.each do |order| %>
					<tr>
						<td><%= order.user %></td>
						<% @trip.destination_specific_activity.items.each do |item| %>
							<td>
								<% order.line_items.each do |line_item| %>
									<%= line_item.quantity if line_item.item_id == item.id %>
								<% end %>
							</td>
						<% end %>
						<td>
							<%= number_to_currency(order.total_amount_due) %>
						</td>
						<td>
							<%= hidden_field_tag "orders[#{order.id}][paid]", '' %>
							<%= check_box_tag "orders[#{order.id}][paid]", true, order.paid %>
							<%#= hidden_field_tag 'orders[][id]', order.id %>
						</td>
					</tr>
				<% end %>
		<tr>
			<td>TOTALS</td>
			<% @trip.destination_specific_activity.items.each do |item| %>
				<td>
					<strong><%= @trip.item_count(item)%></strong>
				</td>
			<% end %>
			<td>
				<strong><%= number_to_currency(@trip.total_amount_due) %></strong>
			</td>
			<td><%= submit_tag 'Save as paid'%></td>
		</tr>
	</table>
	
</p>
</form>
<p>
	<%= link_to 'Publicize trip via email', email_publicize_path(@trip.id) %>
</p>
<p>	
	<%= link_to 'Send email to registered trip participants', email_participants_path(@trip.id) %>
</p>

app/views/trips/_show_footer_nav.html.erb
<p>
<% if (! current_user.nil? && ! @trip.user_registered?(current_user)) || ! user_signed_in? %>
<%= link_to 'Click here to register for this trip.', new_order_path(@trip.id) %>
<%# I created a custom named route to be able to include the trip_id in the url. This is not OOB functionality. %>

<% else %>
	<%= link_to 'Click here to modify your registration for this trip.', edit_order_path(@order.id) %>
<% end %>
</p>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/email_participants_new.html.erb
<h2>Send an email to registered trip participants</h2>
<%= form_tag(email_participants_create_path(@trip.id)) %>
	<div class="field">
		<%= label_tag :subject %>
		<%= text_field_tag :subject, nil, size: 100 %>
	</div>
	<div class="field">
		<%= label_tag :message %>
		<%= text_area_tag :message, nil, rows: 10, cols: 100 %>
	</div>

	<div class="actions">
		<%= submit_tag 'Submit'%>
	</div>
</form>

app/views/trips/email_publicize_new.html.erb
<h2>Publicize trip via email</h2>
<%= form_tag(email_publicize_create_path(@trip.id)) %>
	<div class="field">
		<%= label_tag :message %>
		<%= text_area_tag :message, @trip.publicize_text, rows: 10, cols: 100 %>
	</div>
	<b>A link to the trip's public page is automatically included in the email.</b>
	<div class="field">
		<%= label_tag :email_addresses_separated_by_commas %>
		<%= text_area_tag :addresses, nil, rows: 10, cols: 100 %>
	</div>
	<div class="actions">
		<%= submit_tag 'Submit'%>
	</div>
</form>

app/views/trips/index.html.erb
<h1>Upcoming trips</h1>

<table>
  <tr>
    <th>Group</th>
    <th>Destination</th>
    <th>Activity</th>
    <th>Date</th>
    <th>Leader</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trips.each do |trip| %>
  <tr>
    <td><%= trip.group %></td>
    <td><%= trip.destination_specific_activity.destination.name %></td>
    <td><%= trip.destination_specific_activity.activity.name %></td>
    <td><%= trip.date %></td>
    <td><%= trip.leader %></td>
    
    <td><%= link_to 'Show details', trip %></td>
	<% if current_user.is_trip_leader?(trip) %>    
    	<td><%= link_to 'Edit', edit_trip_path(trip) %></td>
    	<td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%#= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/public_show.html.erb
<h2>Trip Information for Participants</h2>
<p>
  <b>Group:</b>
  <%= @trip.group %>
</p>

<p>
  <b> Activity:</b>
  <%= @trip.destination_specific_activity %>
</p>

<p>
  <b>Date:</b>
  <%= @trip.date %>
</p>

<p>
	<b>Destination:</b>
	<%= @trip.destination_specific_activity.destination.name %>
</p>

<p>
  <b>Leader:</b>
  <%= @trip.leader %>
</p>

<h2>Prices</h2>
<ul>
	<% @trip.destination_specific_activity.items.each do |item| %>
		<li><%= item. name + ': ' + number_to_currency(item.price) %></li>
	<% end %>
</ul>
<p>
	
<%= render partial: 'show_footer_nav'%>

app/views/trips/show.html.erb
<p>
  <b>Group:</b>
  <%= @trip.group %>
</p>

<p>
  <b> Activity:</b>
  <%= @trip.destination_specific_activity %>
</p>

<p>
  <b>Date:</b>
  <%= @trip.date %>
</p>

<p>
	<b>Destination:</b>
	<%= @trip.destination_specific_activity.destination.name %>
</p>

<p>
  <b>Leader:</b>
  <%= @trip.leader %>
</p>

<h2>Prices</h2>
<ul>
	<% @trip.destination_specific_activity.items.each do |item| %>
		<li><%= item. name + ': ' + number_to_currency(item.price) %></li>
	<% end %>
</ul>
<p>
	
<% if ! current_user.nil? && current_user.is_trip_leader?(@trip) %>
	<%= render partial: 'leader'%>
<% end %>
</p>
<%= render partial: 'show_footer_nav'%>