config/routes.rb
GroupsyDaisy::Application.routes.draw do
  
  root to: "trips#index"
  
  devise_for :users
  
  get "static/index"

  match 'orders/:id/new' => 'orders#new', :as => :new_order
  match 'trips/public/:id' => 'trips#public_show', as: :public_trip #use public_trip_url(trip_id)
  match 'trips/email_publicize_new/:id' => 'trips#email_publicize_new', as: :email_publicize #email_publicize_path(trip_id)
  match 'trips/email_publicize_create/:id' => 'trips#email_publicize_create', as: :email_publicize_create
  match 'trips/email_participants_new/:id' => 'trips#email_participants_new', as: :email_participants
  match 'trips/email_participants_create/:id' => 'trips#email_participants_create', as: :email_participants_create
  put 'line_items' => 'line_items#update', as: :update_line_items
  put 'orders' => 'orders#update_multiple', as: :update_orders
  
  resources :orders

  resources :line_items

  resources :items

  resources :trips

  resources :groups

  resources :destination_specific_activities

  resources :activities

  resources :destinations

end

app/models/participant.rb
class Participant < ActiveRecord::Base
  #this class is not presently being used. I plan to use it to add individual named participants to an order.
  belongs_to :person
  belongs_to :lead_participant, class_name: 'Person', foreign_key: :lead_participant
  belongs_to :trip
  attr_accessible :lead_participant, :person, :trip
  accepts_nested_attributes_for :person
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @participants }
    end
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
    @participant = Participant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/new
  # GET /participants/new.json
  def new
    @participant = Participant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/1/edit
  def edit
    @participant = Participant.find(params[:id])
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(params[:participant])

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render json: @participant, status: :created, location: @participant }
      else
        format.html { render action: "new" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /participants/1
  # PUT /participants/1.json
  def update
    @participant = Participant.find(params[:id])

    respond_to do |format|
      if @participant.update_attributes(params[:participant])
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy

    respond_to do |format|
      format.html { redirect_to participants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_for(@participant) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @participant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :person %><br />
    <%= f.text_field :person %>
  </div>
  <div class="field">
    <%= f.label :lead_participant %><br />
    <%= f.number_field :lead_participant %>
  </div>
  <div class="field">
    <%= f.label :trip %><br />
    <%= f.text_field :trip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<h1>Listing participants</h1>

<table>
  <tr>
    <th>Person</th>
    <th>Lead participant</th>
    <th>Trip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @participants.each do |participant| %>
  <tr>
    <td><%= participant.person %></td>
    <td><%= participant.lead_participant %></td>
    <td><%= participant.trip %></td>
    <td><%= link_to 'Show', participant %></td>
    <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
    <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<h1>New participant</h1>

<%= render 'form' %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p>
  <b>Person:</b>
  <%= @participant.person %>
</p>

<p>
  <b>Lead participant:</b>
  <%= @participant.lead_participant %>
</p>

<p>
  <b>Trip:</b>
  <%= @participant.trip %>
</p>


<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>